services:
  # Frontend Service
  - type: web
    name: chatapp-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    buildCommand: ""
    startCommand: ""
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: chatapp-backend
          property: host

  # Backend Service  
  - type: web
    name: chatapp-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: AI_ENABLED
        value: false
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chatapp-postgres
          property: connectionString

databases:
  - name: chatapp-postgres
    databaseName: chatbot_db
    user: chatbot_user
    plan: free 